**LSE Data Science Institute | DS105M 2022 Week10**

**Topic:** Unstructured Data

**Author:** [@jonjoncardoso](github.com/jonjoncardoso)

**Date:** 29 November 2022

---

Obs: If you did not attend the lecture, you might notice a few gaps in your understanding when following this notebook. Watch the lecture recording.

# Why care about unstructured data?

Most datasets do not come in a tidy format that can fit perfectly well in a data frame (a structured data format). That is the case, for example, of **text data**.

# Working with Twitter Data

We will use [tweepy](https://docs.tweepy.org/en/stable/getting_started.html) library to access Twiter API.

The first thing we have to do is authenticate:

## 🚨🚨🚨🚨KEEP SECRETS OUT! 🚨🚨🚨🚨

EXTREMELY EXTREMELY IMPORTANT ADVICE:

- Don't use your SSH keys ANYWHERE in this notebook. Also, don't put them on Github either!!!
- Instead, create a `config.py` file somewhere outside this project (or .gitignore this file). See for example [this Stackoverflow link](https://stackoverflow.com/a/25501861/843365)

In [1]:
import config # This loads the content of the config.py file. If this throws an error, it is because you haven't created a config.py!

## Establish a connection

In [3]:
import tweepy

client = tweepy.Client(bearer_token=config.bearer_token, 
                       consumer_key=config.api_key, 
                       consumer_secret=config.api_key_secret, 
                       access_token=config.access_token, 
                       access_token_secret=config.access_token_secret)

## Obtain a few tweets just to test this works:

In [3]:
public_tweets = client.search_recent_tweets(query="Qatar")

# What is the format of the data returned?
public_tweets

Response(data=[<Tweet id=1599775387872919552 text='RT @tendenciasposta: "#Mbappé🏳️\u200d🌈":\nPorque fue deportado de Qatar junto a Giroud. https://t.co/BxfeqKmfJI'>, <Tweet id=1599775387797463041 text='RT @sk_bongomin93: Qatar put their whole in crafting these world cup stadia, it could turn into a night club anytime, the world was jamming…'>, <Tweet id=1599775386975424512 text='RT @solopasaenperu: "No estoy en Qatar, estoy en el mundial" https://t.co/0MIcm7GJXm'>, <Tweet id=1599775386933813249 text='The @NYCMayor is in #Qatar for the #WorldcupQatar2022 while the city continues to go to shit. #priorities'>, <Tweet id=1599775385490972673 text='🇲🇽 El ‘Tata’ Martino regresa a #México entre abucheos e insultos\n\n❌ Los hinchas del #Tri y reporteros no perdonaron la eliminación del seleccionado mexicano en el #Mundial de #Qatar \n\nhttps://t.co/u3asQbRxEz'>, <Tweet id=1599775383712591873 text='RT @FreeLiveLink: 🔴𝐆𝐨 𝐎𝐧 𝐋𝐢𝐯𝐞📺@worldcuplivestv\n\nWatch 2022 FIFA World Cup Football/Soccer Match Round Of 16 Live Streams Online Free Score,…'>, <Tweet id=1599775383569719296 text='Mundial de Qatar 2022: cómo es la semana de la Selección Argentina antes del partido con Países Bajos | Deportes https://t.co/55BNWHNJt5'>, <Tweet id=1599775382483259392 text='Panini Fifa World Cup Qatar 2022 Album Stickers Qatar World Cup Official Football Star Collection Sticker Creative Fan\xa0Gifts https://t.co/G5HvTuLWWC'>, <Tweet id=1599775382311301120 text='@Chron_job @hilarykaior @Lynchchadtheog @mustxrd_ @VeggieBlue @ExiledAstrix4 @iss_zaba @Alexmitton10 @Qatari @thfckei You already look tired after being thrashed due to illogical arguments you bring to the table but let me make it easy for you. You came to Qatar earning a dollar figure which you wouldnt have made in ur own country while keeping a blind eye to all the ..'>, <Tweet id=1599775379946106881 text='RT @sk_bongomin93: Qatar put their whole in crafting these world cup stadia, it could turn into a night club anytime, the world was jamming…'>], includes={}, errors=[], meta={'newest_id': '1599775387872919552', 'oldest_id': '1599775379946106881', 'result_count': 10, 'next_token': 'b26v89c19zqg8o3fpzhn0g00o9u43e6gu1kzsejcv0gal'})

**What kind of data is returned?**

💡 From the [tweepy's Response documentation](https://docs.tweepy.org/en/stable/response.html#tweepy.Response), we read that this object is of a particular data type called [named tuple](https://realpython.com/python-namedtuple/#using-namedtuple-to-write-pythonic-code).  It is kind of a dictionary, there are fields with names that contain data inside them:

In [4]:
type(public_tweets)

tweepy.client.Response

In [15]:
public_tweets._fields

('data', 'includes', 'errors', 'meta')

In [16]:
public_tweets.data

[<Tweet id=1597576494720888837 text='“Não pode isso e aquilo no Qatar…”\nMas eles não contavam q o brasileiro tem um coisa mto apaixonante: a alegria! https://t.co/J1T1b5l2Xg'>,
 <Tweet id=1597576494628208640 text='Netherlands wins \nNetherlands 2 - 1 Qatar https://t.co/DUtWhDfIBa'>,
 <Tweet id=1597576494553133056 text='RT @PMU_Sport: 🔮 Les prédictions de @ReveilAudrey &amp; de @NeauMali pour Pays-Bas // Qatar !\n\n🤔 Vous êtes #TeamPaysBas ou #TeamQatar ?\n🔃 RT +…'>,
 <Tweet id=1597576494511173632 text='RT @VTVcanal8: #Qatar2022⚽| Disfruta con nosotros todos los encuentros, análisis, estadísticas, mejores jugadas y mucho más con los mejores…'>,
 <Tweet id=1597576494112727040 text="Vraiment a mes yeux les matchs comme ça y a pas + inutile 😭 On sait tous très bien que le Qatar va ce faire ouvrir en 2 mais on s'emmerde a faire un match 😭 https://t.co/QV4xN7cYab">,
 <Tweet id=1597576493810475009 text='RT @cfootcameroun: «\xa0Je n’ai pas de problème avec mon grand frère Ernest Obama, j’ai été puni par le président Eto’o et le coach Rigobert S…'>,
 <Tweet id=1597576493429035008 text='RT @TheMancUK: He also showed his support for Ukraine and women in Iran. 🏳️\u200d🌈❤️👏https://t.co/aAr44M4W9C'>,
 <Tweet id=1597576493252882432 text='RT @ParikPatelCFA: The USA vs Iran game in Qatar tomorrow will be the first time the US is fighting in the Middle East without looking for…'>,
 <Tweet id=1597576492833452032 text='RT @Football__Tweet: 🚨 Mario Ferri, the pitch invader from last night, has announced that he has been released by Qatar without being sanct…'>,
 <Tweet id=1597576492514410497 text='OM : Longoria aperçu au Qatar, que mijote-t-il ? https://t.co/YQj9tTtCRm'>]

In [21]:
public_tweets.meta

{'newest_id': '1597576494720888837',
 'oldest_id': '1597576492514410497',
 'result_count': 10,
 'next_token': 'b26v89c19zqg8o3fpzhm60iol0r4ixtrpxfityowxs1h9'}

**Interesting...**

🤔 Hmmm so we learn that our query has returned only 10 results and from the documentation, we read that `next_token` is used to paginate. This applies to all APIS: when in doubt, check the documentation!

Let's look at the next page then:

In [25]:
client.search_recent_tweets(query="Qatar", next_token='b26v89c19zqg8o3fpzhm60iol0r4ixtrpxfityowxs1h9')

Response(data=[<Tweet id=1597576491247624192 text="Migrant workers were deceived and died for Qatar's World Cup. Thousands want compensation https://t.co/8hwISaR45a">, <Tweet id=1597576490723704832 text='RT @binnahar85: Criticising Qatar this way or another is not an issue, it is actually a basic right.\nThe issue here is hypocrisy. Did u do…'>, <Tweet id=1597576490065219585 text='RT @PMU_Sport: 🔮 Les prédictions de @ReveilAudrey &amp; de @NeauMali pour Pays-Bas // Qatar !\n\n🤔 Vous êtes #TeamPaysBas ou #TeamQatar ?\n🔃 RT +…'>, <Tweet id=1597576490061033472 text='RT @_mydeszn: I’m live in Qatar. 🇶🇦❤️✨, and yes I’m actually a white Nigerian https://t.co/pH5WPgtqqs'>, <Tweet id=1597576488987291648 text='RT @HananyaNaftali: The best joke of the World Cup:\n\nQatar wants to lecture Israel on human rights. 😂 #WorldCup2022 #FIFA https://t.co/3pb4…'>, <Tweet id=1597576487745781760 text='RT @RusEmbIran: Moscow has supported the national team of 🇮🇷Iran before the decisive ⚽️football match with the United States at the 2022 Wo…'>, <Tweet id=1597576487686836225 text='CdM : Benzema apte à rejoindre les Bleus au Qatar ? Voici la réponse ! https://t.co/33t4iSDFyW'>, <Tweet id=1597576487162777601 text='#Qatar2022 \n#Qatar https://t.co/iQuByEP4ld'>, <Tweet id=1597576486542016513 text='RT @VTVcanal8: #Qatar2022⚽| Aquí te mostramos los resultados del Mundial de Fútbol Qatar 2022, correspondientes a la jornada de este #28Nov…'>, <Tweet id=1597576485862268930 text='De meest ontroerende scènes op het WK in Qatar: van dansje voor zieke Finlay (11) tot tranen om overleden vader https://t.co/f03ERoUj1s'>], includes={}, errors=[], meta={'newest_id': '1597576491247624192', 'oldest_id': '1597576485862268930', 'result_count': 10, 'next_token': 'b26v89c19zqg8o3fpzhm60iol0r3gidov4hh073543k3h'})

## What are people talking about LSE on Twitter?

In [4]:
tweet_fields=["id", "text", "attachments", "author_id", "context_annotations", "conversation_id", 
              "created_at", "entities", "in_reply_to_user_id", "lang", "public_metrics", "geo"]

In [23]:
lse_tweets = client.search_recent_tweets(query="Qatar", 
                                         tweet_fields=tweet_fields,
                                         user_fields="location",
                                         max_results=100)

In [24]:
tweet = lse_tweets.data[0]
tweet.geo

In [31]:
tweet.entities

{'mentions': [{'start': 3,
   'end': 16,
   'username': 'HoyPalestina',
   'id': '1258174836175704064'}],
 'urls': [{'start': 96,
   'end': 119,
   'url': 'https://t.co/UyULSbvoFs',
   'expanded_url': 'https://twitter.com/HoyPalestina/status/1599761913465880577/video/1',
   'display_url': 'pic.twitter.com/UyULSbvoFs',
   'media_key': '7_1599761850454900739'}]}

In [30]:
dir(tweet)

['__abstractmethods__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '_abc_impl',
 'attachments',
 'author_id',
 'context_annotations',
 'conversation_id',
 'created_at',
 'data',
 'edit_controls',
 'edit_history_tweet_ids',
 'entities',
 'geo',
 'get',
 'id',
 'in_reply_to_user_id',
 'items',
 'keys',
 'lang',
 'non_public_metrics',
 'organic_metrics',
 'possibly_sensitive',
 'promoted_metrics',
 'public_metrics',
 'referenced_tweets',
 'reply_settings',
 'source',
 'text',
 'values',
 'withheld']

In [28]:
dir(lse_tweets.data[0])

['__abstractmethods__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '_abc_impl',
 'attachments',
 'author_id',
 'context_annotations',
 'conversation_id',
 'created_at',
 'data',
 'edit_controls',
 'edit_history_tweet_ids',
 'entities',
 'geo',
 'get',
 'id',
 'in_reply_to_user_id',
 'items',
 'keys',
 'lang',
 'non_public_metrics',
 'organic_metrics',
 'possibly_sensitive',
 'promoted_metrics',
 'public_metrics',
 'referenced_tweets',
 'reply_settings',
 'source',
 'text',
 'values',
 'withheld']

**Who tweeted that?**

In [25]:
[tweet.geo for tweet in lse_tweets.data]

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [18]:
tweet.author_id

311244158

In [19]:
client.get_user(id=lse_tweets.data[0].author_id)

Response(data=<User id=311244158 name=Eliana Jung Duran username=e_jungd>, includes={}, errors=[], meta={})

# Best Practices

In [ ]:
#### DATA COLLECTION ###

# 1. Create a CSV file 

# 2. Read it
df_politicians = pd.read_csv("politicians.csv")

# 3 Create a function
def get_all_tweets(username):
    ....
    <Suggestion: collect everything you can from the tweets, not just the text>
    
    <Things you can consider collecting ["id", "text", "attachments", "author_id", "context_annotations", "conversation_id", 
              "created_at", "entities", "in_reply_to_user_id", "lang", "public_metrics", "geo"]>
    ....
    return df_all_tweets # for a particular user

# 4 Collect all information
df_all_tweets = pd.concat([get_all_tweets(username) for username in df_politicians["username"]])

# 5 Save it as a CSV file


##### PRE-PROCESSING OR ANALYSIS PART

...in a separate file...

# Let's create a `tidy` dataframe

In [20]:
import pandas as pd

In [25]:
{field: tweet[field] for field in ["author_id", "text", "created_at", "lang"]}

{'author_id': 1541466817633419264,
 'text': "György left Hungary in 1947 and studied economics at the London School of Economics, where he received a bachelor's degree in 1951 and a PhD in 1954.",
 'created_at': datetime.datetime(2022, 11, 28, 21, 40, 31, tzinfo=datetime.timezone.utc),
 'lang': 'en'}

In [27]:
df = pd.concat([pd.DataFrame({field: tweet[field] 
                              for field in ["author_id", "text", "created_at", "lang"]}, index=[tweet["id"]]) 
                for tweet in lse_tweets.data])

In [74]:
df

,author_id,text,created_at,lang
1597574950415638528,63684604,Director of International Programmes and Impac...,2022-11-29 12:55:24+00:00,en
1597574643489312769,236346971,RT @fascinatorfun: “That amounts to a loss of ...,2022-11-29 12:54:11+00:00,en
1597573860890931200,442976787,The London School of Economics has estimated t...,2022-11-29 12:51:04+00:00,en
1597572812923088897,276442577,RT @fascinatorfun: “That amounts to a loss of ...,2022-11-29 12:46:54+00:00,en
1597571481667768320,188690239,RT @lag_uk: 📢We are pleased to award the 2022 ...,2022-11-29 12:41:37+00:00,en
...,...,...,...,...
1597321824215650304,1159888310891945985,@philerator @phlannelphysics @bleasdale_r @The...,2022-11-28 20:09:34+00:00,en
1597318449336037376,4328654057,[Κλικ και διαβάστε στο ΠΡΩΤΟ ΘΕΜΑ]Δείτε live: ...,2022-11-28 19:56:09+00:00,el
1597317637117464577,1442770309694754821,Στην εκδήλωση του Ελληνικού Παρατηρητηρίου του...,2022-11-28 19:52:56+00:00,el
1597317226960502784,4328654057,[Κλικ και διαβάστε στο ΠΡΩΤΟ ΘΕΜΑ]Δείτε live: ...,2022-11-28 19:51:18+00:00,el
1597316899246903297,934448438,Μητσοτάκης μετά τη συνάντηση με Κάρολο: Μπορεί...,2022-11-28 19:50:00+00:00,el

**Let's add the author_id username!**

There is a simpler way to do this, but I want to use this to demonstrate the concept of `merge`

In [28]:
df["author_id"].nunique()

98

In [29]:
all_authors = df["author_id"].unique()
all_authors

array([          311244158,            74883793,  930217579800604672,
       1497870550332579845,           940224440,            77174319,
                  48548972,  843245260088229890,           211221275,
        852575123999780864,          2425846856,  739730879770198017,
                 577431005, 1087467579751452672, 1554576805373296640,
       1061233680570556418,          1489899626,          1911206232,
       1290481714393780228,            39450170, 1007404152278929410,
       1293301271890460672, 1062397828650164227,          3030504268,
                 717983004,           322661351,          3131500904,
        874613730985861121, 1496217735948345345, 1382409342998229004,
       1029382765664501762, 1261552344724049920,          2753943800,
                  63684604,           236346971,           442976787,
                 276442577,           188690239, 1496957719982579712,
                 283549521,           578444253,           283604227,
                 105806085,          2171907357,           146543890,
       1024939332686307328,           303875086,  947433002795184129,
                 297915262,           126597444,          2912442951,
       1002515918323404800,           351637790,           282914879,
       1282744796935868422,           548521594, 1581543998090579968,
       1586632345129742336,           121517017,          1563454808,
                 300790937,          2826788653, 1500412236053061636,
                 245079791, 1597274172148912131,  750192467652280320,
                3371856143,           253557119, 1144377703426138112,
       1443642054370807815,           615987418, 1329483502077825025,
                 334888674,          1460958716,           896382234,
                1652342700,           104473312, 1588421382412591107,
       1253921902755811335,  731036953295097856,           327267369,
        956498128907227136, 1484347464161185798,            53346239,
        961223387044442112,  846141344535916544, 1097864161021825026,
       1359791563170275328,          2789390689, 1425378621363945483,
                 373909732,           191434404, 1495800862400290826,
                2579454504, 1113426385974984705,          1527074713,
                  38631911, 1541466817633419264], dtype=int64)

**Use `list comprehension` to obtain author_usernames**

In [37]:
client.get_user(id=38631911).data["username"]

'B3CPres'

In [161]:
[client.get_user(id=author_id) for author_id in all_authors]

[Response(data=<User id=63684604 name=Guardian Exec Jobs username=GJ_Exec>, includes={}, errors=[], meta={}),
 Response(data=<User id=236346971 name=Bob Massam #FBPE🔶💙 username=bmassam>, includes={}, errors=[], meta={}),
 Response(data=<User id=442976787 name=Ros Chappell 🇺🇦StandWithUkraine ⭐️UK Rejoin 🇪🇺 username=RosChappell>, includes={}, errors=[], meta={}),
 Response(data=<User id=276442577 name=12Pat username=StarterPat>, includes={}, errors=[], meta={}),
 Response(data=<User id=188690239 name=Sam Halvorsen username=samhalvorsen>, includes={}, errors=[], meta={}),
 Response(data=<User id=1496957719982579712 name=M P username=mexxez16>, includes={}, errors=[], meta={}),
 Response(data=<User id=283549521 name=Matthew Aaron Richmond username=mattyrichy>, includes={}, errors=[], meta={}),
 Response(data=<User id=578444253 name=Dominique username=dominiquelevack>, includes={}, errors=[], meta={}),
 Response(data=<User id=283604227 name=Andy Vermaut username=AndyVermaut>, includes={}, errors=[], meta={}),
 Response(data=<User id=105806085 name=Itzel San Roman Pineda username=itzelsanroman>, includes={}, errors=[], meta={}),
 Response(data=<User id=2171907357 name=Chris Gough username=clickoncopy>, includes={}, errors=[], meta={}),
 Response(data=<User id=146543890 name=KayB🕷 username=1_Lovelife>, includes={}, errors=[], meta={}),
 Response(data=<User id=1024939332686307328 name=Latin American Geographies-UK username=lag_uk>, includes={}, errors=[], meta={}),
 Response(data=<User id=303875086 name=Ruth Campbell username=RuthCampbell1>, includes={}, errors=[], meta={}),
 Response(data=<User id=947433002795184129 name=Paul Allen #RejoinEU-ASAP username=PaulAllenSK1>, includes={}, errors=[], meta={}),
 Response(data=<User id=297915262 name=Peter Howells #RejoinEU #FBPE #FBPPR 🇪🇺 username=Peter__Howells>, includes={}, errors=[], meta={}),
 Response(data=<User id=126597444 name=Mrs Trevithick username=MrsTrevithick>, includes={}, errors=[], meta={}),
 Response(data=<User id=2912442951 name=canog 🇺🇦 #StandsWithUkraine aka @canog@mastodon username=canogbiz>, includes={}, errors=[], meta={}),
 Response(data=<User id=1002515918323404800 name=Chromophilia username=ChromophiliaUK>, includes={}, errors=[], meta={}),
 Response(data=<User id=351637790 name=Paul O'Connor 🇮🇪 🇬🇧 🇪🇺 🇺🇦 #GTTO #BLM username=BrixDez>, includes={}, errors=[], meta={}),
 Response(data=<User id=282914879 name=Fionna O'Leary, 🕯🇪🇺 username=fascinatorfun>, includes={}, errors=[], meta={}),
 Response(data=<User id=1282744796935868422 name=MrJPCarter username=MrJPCarter1>, includes={}, errors=[], meta={}),
 Response(data=<User id=548521594 name=Πολίτης Του Κόσμου username=PolitisTkosmou>, includes={}, errors=[], meta={}),
 Response(data=<User id=1581543998090579968 name=Φαιστιβαλ Conne Ωδειγιτή username=NikosKoudounis1>, includes={}, errors=[], meta={}),
 Response(data=<User id=1586632345129742336 name=The Madras Tribe 🪶 username=MadrasTribes>, includes={}, errors=[], meta={}),
 Response(data=<User id=121517017 name=maddingcrowd username=maddingcrowd07>, includes={}, errors=[], meta={}),
 Response(data=<User id=1563454808 name=LSE USAPP blog username=LSEUSAblog>, includes={}, errors=[], meta={}),
 Response(data=<User id=300790937 name=AgainstAllWars🏴‍☠️🪐🦾☘️ username=S2t2n>, includes={}, errors=[], meta={}),
 Response(data=<User id=2826788653 name=Dame Teacher of South London #RejoinEU #NHS#GTTO username=1to1teachers>, includes={}, errors=[], meta={}),
 Response(data=<User id=1500412236053061636 name=Sassy username=sassyheren>, includes={}, errors=[], meta={}),
 Response(data=<User id=245079791 name=Dave Madden 🇪🇺 username=redmadden>, includes={}, errors=[], meta={}),
 Response(data=<User id=1597274172148912131 name=SFT 210 username=sft_210>, includes={}, errors=[], meta={}),
 Response(data=<User id=750192467652280320 name=@pleaseletmevote username=pleaseletmevote>, includes={}, errors=[], meta={}),
 Response(data=<User id=3371856143 name=Tha Noto username=AthaNoto>, includes={}, errors=[], meta={}),
 Response(data=<User id=253557119 name=Dana mulina username=mulina_cz>, includes={}, errors=[], meta={}),
 Response(data=<User id=1144377703426138112 name=Deppy username=Deppy90890092>, includes={}, errors=[], meta={}),
 Response(data=<User id=1443642054370807815 name=Μαριάννα Φρερη username=tu265ikJ4G3iLxZ>, includes={}, errors=[], meta={}),
 Response(data=<User id=615987418 name=atlas9023 username=atlas9023>, includes={}, errors=[], meta={}),
 Response(data=<User id=1329483502077825025 name=Gerontompempek@ username=gerontompempek>, includes={}, errors=[], meta={}),
 Response(data=<User id=334888674 name=Paula Ph. 🐾🐾 username=dacandia13>, includes={}, errors=[], meta={}),
 Response(data=<User id=1460958716 name=Κapoios Αllos 🌐 username=Kapoiosmpla>, includes={}, errors=[], meta={}),
 Response(data=<User id=896382234 name=EFSYN username=EFSYNTAKTON>, includes={}, errors=[], meta={}),
 Response(data=<User id=1652342700 name=Pasco Nkololo username=Nkololotz>, includes={}, errors=[], meta={}),
 Response(data=<User id=104473312 name=Charles Rue username=Charles_Rue>, includes={}, errors=[], meta={}),
 Response(data=<User id=1588421382412591107 name=Mtz (parodi) username=tanzaniaRt>, includes={}, errors=[], meta={}),
 Response(data=<User id=1253921902755811335 name=Export Processing Zones Authority username=Tanzania_epza>, includes={}, errors=[], meta={}),
 Response(data=<User id=731036953295097856 name=Μανωλοπούλου Νατασα username=Masprixate>, includes={}, errors=[], meta={}),
 Response(data=<User id=327267369 name=Nikos Chatzinikolaou username=NChatzinikolaou>, includes={}, errors=[], meta={}),
 Response(data=<User id=956498128907227136 name=Jenny username=Jennifer_chm002>, includes={}, errors=[], meta={}),
 Response(data=<User id=1484347464161185798 name=E J username=EJ03753321>, includes={}, errors=[], meta={}),
 Response(data=<User id=53346239 name=Sigmalive username=Sigmalivecom>, includes={}, errors=[], meta={}),
 Response(data=<User id=961223387044442112 name=BG 🖤 username=joBeeGeorgeous>, includes={}, errors=[], meta={}),
 Response(data=<User id=846141344535916544 name=GCB username=baby_beemer00>, includes={}, errors=[], meta={}),
 Response(data=<User id=1097864161021825026 name=Dharmendra singh username=Dharmen69191019>, includes={}, errors=[], meta={}),
 Response(data=<User id=1359791563170275328 name=circuit laundry bot username=BotCircuit>, includes={}, errors=[], meta={}),
 Response(data=<User id=2789390689 name=marhaen but not really username=NadsMarhaen>, includes={}, errors=[], meta={}),
 Response(data=<User id=1425378621363945483 name=Mariana Ruiz username=Marianarrrrrrz>, includes={}, errors=[], meta={}),
 Response(data=<User id=373909732 name=enikos.gr username=enikos_gr>, includes={}, errors=[], meta={}),
 Response(data=<User id=191434404 name=Michael Hainsworth username=hainsworthtv>, includes={}, errors=[], meta={}),
 Response(data=<User id=1495800862400290826 name=SPO_POWER username=SPO_Power>, includes={}, errors=[], meta={}),
 Response(data=<User id=2579454504 name=AGomes username=xpgomes3>, includes={}, errors=[], meta={}),
 Response(data=<User id=1113426385974984705 name=Professor Linda Mulcahy username=LindaMulcahy7>, includes={}, errors=[], meta={}),
 Response(data=<User id=1527074713 name=Ant1news.gr username=AntennaNews>, includes={}, errors=[], meta={}),
 Response(data=<User id=38631911 name=Jonathan Price username=B3CPres>, includes={}, errors=[], meta={}),
 Response(data=<User id=1541466817633419264 name=TraderHustler username=TraderRembrandt>, includes={}, errors=[], meta={}),
 Response(data=<User id=916233147033014272 name=Rodney Leigh Care username=LeighCare>, includes={}, errors=[], meta={}),
 Response(data=<User id=1550534589210296324 name=Eric Clafton username=Tsarumon1>, includes={}, errors=[], meta={}),
 Response(data=<User id=2838358556 name=BITSS username=UCBITSS>, includes={}, errors=[], meta={}),
 Response(data=<User id=193680125 name=Stevi - 🇺🇦 #StandWithUkraine #DetestToryValues username=steviweavi>, includes={}, errors=[], meta={}),
 Response(data=<User id=340498991 name=Tina Jane White username=tina_jane>, includes={}, errors=[], meta={}),
 Response(data=<User id=19685010 name=Sian Jasper username=SianJasper>, includes={}, errors=[], meta={}),
 Response(data=<User id=611754326 name=Sue Austin #GENERALELECTIONNOW #GETPRDONE username=sue21320>, includes={}, errors=[], meta={}),
 Response(data=<User id=1533822985 name=Ain't too Shabby username=ainttooshabbyuk>, includes={}, errors=[], meta={}),
 Response(data=<User id=34919012 name=..... username=turks22>, includes={}, errors=[], meta={}),
 Response(data=<User id=798652412626161664 name=Dame Carol Voldermort 🇺🇦 username=carolvolders>, includes={}, errors=[], meta={}),
 Response(data=<User id=774510439824822273 name=Brexit Bin 🇪🇺🇬🇧🇩🇪🕊🇺🇦 #BrexitReality username=BrexitBin>, includes={}, errors=[], meta={}),
 Response(data=<User id=1498629847324807169 name=Raven__ous username=MelinaPavlakou>, includes={}, errors=[], meta={}),
 Response(data=<User id=2200853882 name=TheTOC username=TheTOC_gr>, includes={}, errors=[], meta={}),
 Response(data=<User id=1074572804 name=newmoney.gr username=newmoneygr>, includes={}, errors=[], meta={}),
 Response(data=<User id=2389692329 name=College of Humanities & Social Sciences at Rowan username=RowanCHSS>, includes={}, errors=[], meta={}),
 Response(data=<User id=59202489 name=M. Drakomathioulakis username=bageragr>, includes={}, errors=[], meta={}),
 Response(data=<User id=1468691256171806726 name=sotiris@ username=papanatos_>, includes={}, errors=[], meta={}),
 Response(data=<User id=1358745630533955586 name=ot.gr username=otgr_official>, includes={}, errors=[], meta={}),
 Response(data=<User id=1497870550332579845 name=MpoumpouLina username=LinaMpoumpou>, includes={}, errors=[], meta={}),
 Response(data=<User id=4103637017 name=mononewsgr username=mononewsgr>, includes={}, errors=[], meta={}),
 Response(data=<User id=1586184488245141504 name=JScott username=JScottHolt47>, includes={}, errors=[], meta={}),
 Response(data=<User id=268283495 name=Το Παρασκήνιο username=paraskhnio>, includes={}, errors=[], meta={}),
 Response(data=<User id=1159888310891945985 name=Kevin Alexanderman username=k_alexanderman>, includes={}, errors=[], meta={}),
 Response(data=<User id=4328654057 name=presshub.gr username=presshub_gr>, includes={}, errors=[], meta={}),
 Response(data=<User id=1442770309694754821 name=gegonota.news username=Gegonota_News>, includes={}, errors=[], meta={}),
 Response(data=<User id=934448438 name=RP.GR username=RP_GR_2020>, includes={}, errors=[], meta={})]

**That took quite some time... How do we check if my code is stuck?**

💡Use a library called tqdm for progress bar:

In [38]:
import tqdm

author_usernames = [client.get_user(id=author_id).data["username"] for author_id in tqdm.tqdm(all_authors)]

  0%|                                                               | 0/98 [00:00<?, ?it/s]

  1%|▌                                                      | 1/98 [00:00<00:18,  5.33it/s]

  2%|█                                                      | 2/98 [00:00<00:17,  5.40it/s]

  3%|█▋                                                     | 3/98 [00:00<00:18,  5.06it/s]

  4%|██▏                                                    | 4/98 [00:00<00:18,  4.98it/s]

  5%|██▊                                                    | 5/98 [00:00<00:18,  4.93it/s]

  6%|███▎                                                   | 6/98 [00:01<00:18,  4.95it/s]

  7%|███▉                                                   | 7/98 [00:01<00:18,  4.92it/s]

  8%|████▍                                                  | 8/98 [00:01<00:18,  4.91it/s]

  9%|█████                                                  | 9/98 [00:01<00:16,  5.50it/s]

 10%|█████▌                                                | 10/98 [00:01<00:15,  5.59it/s]

 11%|██████                                                | 11/98 [00:02<00:16,  5.39it/s]

 12%|██████▌                                               | 12/98 [00:02<00:16,  5.18it/s]

 13%|███████▏                                              | 13/98 [00:02<00:16,  5.08it/s]

 14%|███████▋                                              | 14/98 [00:02<00:16,  5.09it/s]

 15%|████████▎                                             | 15/98 [00:02<00:16,  4.95it/s]

 16%|████████▊                                             | 16/98 [00:03<00:16,  4.94it/s]

 17%|█████████▎                                            | 17/98 [00:03<00:16,  4.94it/s]

 18%|█████████▉                                            | 18/98 [00:03<00:14,  5.51it/s]

 19%|██████████▍                                           | 19/98 [00:03<00:14,  5.59it/s]

 20%|███████████                                           | 20/98 [00:03<00:13,  5.94it/s]

 21%|███████████▌                                          | 21/98 [00:03<00:12,  5.95it/s]

 22%|████████████                                          | 22/98 [00:04<00:13,  5.63it/s]

 23%|████████████▋                                         | 23/98 [00:04<00:12,  6.08it/s]

 24%|█████████████▏                                        | 24/98 [00:04<00:12,  5.95it/s]

 26%|█████████████▊                                        | 25/98 [00:04<00:13,  5.56it/s]

 27%|██████████████▎                                       | 26/98 [00:04<00:13,  5.32it/s]

 28%|██████████████▉                                       | 27/98 [00:05<00:12,  5.47it/s]

 29%|███████████████▍                                      | 28/98 [00:05<00:11,  5.92it/s]

 30%|███████████████▉                                      | 29/98 [00:05<00:12,  5.57it/s]

 31%|████████████████▌                                     | 30/98 [00:05<00:12,  5.35it/s]

 32%|█████████████████                                     | 31/98 [00:05<00:12,  5.22it/s]

 33%|█████████████████▋                                    | 32/98 [00:06<00:12,  5.20it/s]

 34%|██████████████████▏                                   | 33/98 [00:06<00:12,  5.03it/s]

 35%|██████████████████▋                                   | 34/98 [00:06<00:14,  4.40it/s]

 36%|███████████████████▎                                  | 35/98 [00:06<00:12,  5.00it/s]

 37%|███████████████████▊                                  | 36/98 [00:06<00:12,  5.10it/s]

 38%|████████████████████▍                                 | 37/98 [00:07<00:12,  5.05it/s]

 39%|████████████████████▉                                 | 38/98 [00:07<00:10,  5.66it/s]

 40%|█████████████████████▍                                | 39/98 [00:07<00:10,  5.57it/s]

 41%|██████████████████████                                | 40/98 [00:07<00:10,  5.39it/s]

 42%|██████████████████████▌                               | 41/98 [00:07<00:10,  5.28it/s]

 43%|███████████████████████▏                              | 42/98 [00:07<00:11,  5.07it/s]

 44%|███████████████████████▋                              | 43/98 [00:08<00:10,  5.02it/s]

 45%|████████████████████████▏                             | 44/98 [00:08<00:09,  5.55it/s]

 46%|████████████████████████▊                             | 45/98 [00:08<00:09,  5.83it/s]

 47%|█████████████████████████▎                            | 46/98 [00:08<00:09,  5.36it/s]

 48%|█████████████████████████▉                            | 47/98 [00:08<00:08,  5.68it/s]

 49%|██████████████████████████▍                           | 48/98 [00:08<00:08,  5.86it/s]

 50%|███████████████████████████                           | 49/98 [00:09<00:08,  5.54it/s]

 51%|███████████████████████████▌                          | 50/98 [00:09<00:09,  5.29it/s]

 52%|████████████████████████████                          | 51/98 [00:09<00:08,  5.27it/s]

 53%|████████████████████████████▋                         | 52/98 [00:09<00:09,  5.05it/s]

 54%|█████████████████████████████▏                        | 53/98 [00:10<00:08,  5.01it/s]

 55%|█████████████████████████████▊                        | 54/98 [00:10<00:07,  5.54it/s]

 56%|██████████████████████████████▎                       | 55/98 [00:10<00:07,  5.98it/s]

 57%|██████████████████████████████▊                       | 56/98 [00:10<00:06,  6.32it/s]

 58%|███████████████████████████████▍                      | 57/98 [00:10<00:06,  6.07it/s]

 59%|███████████████████████████████▉                      | 58/98 [00:10<00:06,  6.36it/s]

 60%|████████████████████████████████▌                     | 59/98 [00:10<00:05,  6.72it/s]

 61%|█████████████████████████████████                     | 60/98 [00:11<00:05,  6.89it/s]

 62%|█████████████████████████████████▌                    | 61/98 [00:11<00:05,  6.80it/s]

 63%|██████████████████████████████████▏                   | 62/98 [00:11<00:05,  6.29it/s]

 64%|██████████████████████████████████▋                   | 63/98 [00:11<00:05,  5.86it/s]

 65%|███████████████████████████████████▎                  | 64/98 [00:11<00:06,  5.49it/s]

 66%|███████████████████████████████████▊                  | 65/98 [00:11<00:06,  5.29it/s]

 67%|████████████████████████████████████▎                 | 66/98 [00:12<00:05,  5.84it/s]

 68%|████████████████████████████████████▉                 | 67/98 [00:12<00:05,  5.80it/s]

 69%|█████████████████████████████████████▍                | 68/98 [00:12<00:05,  5.46it/s]

 70%|██████████████████████████████████████                | 69/98 [00:12<00:05,  5.32it/s]

 71%|██████████████████████████████████████▌               | 70/98 [00:12<00:05,  5.18it/s]

 72%|███████████████████████████████████████               | 71/98 [00:13<00:04,  5.42it/s]

 73%|███████████████████████████████████████▋              | 72/98 [00:13<00:04,  5.97it/s]

 74%|████████████████████████████████████████▏             | 73/98 [00:13<00:04,  5.50it/s]

 76%|████████████████████████████████████████▊             | 74/98 [00:13<00:04,  5.26it/s]

 77%|█████████████████████████████████████████▎            | 75/98 [00:13<00:04,  5.68it/s]

 78%|█████████████████████████████████████████▉            | 76/98 [00:13<00:03,  6.18it/s]

 79%|██████████████████████████████████████████▍           | 77/98 [00:13<00:03,  6.45it/s]

 80%|██████████████████████████████████████████▉           | 78/98 [00:14<00:02,  6.69it/s]

 81%|███████████████████████████████████████████▌          | 79/98 [00:14<00:02,  6.76it/s]

 82%|████████████████████████████████████████████          | 80/98 [00:14<00:02,  6.93it/s]

 83%|████████████████████████████████████████████▋         | 81/98 [00:14<00:02,  7.06it/s]

 84%|█████████████████████████████████████████████▏        | 82/98 [00:14<00:02,  6.97it/s]

 85%|█████████████████████████████████████████████▋        | 83/98 [00:14<00:02,  7.12it/s]

 86%|██████████████████████████████████████████████▎       | 84/98 [00:14<00:01,  7.18it/s]

 87%|██████████████████████████████████████████████▊       | 85/98 [00:15<00:01,  6.97it/s]

 88%|███████████████████████████████████████████████▍      | 86/98 [00:15<00:01,  7.22it/s]

 89%|███████████████████████████████████████████████▉      | 87/98 [00:15<00:01,  7.24it/s]

 90%|████████████████████████████████████████████████▍     | 88/98 [00:15<00:01,  7.16it/s]

 91%|█████████████████████████████████████████████████     | 89/98 [00:15<00:01,  7.09it/s]

 92%|█████████████████████████████████████████████████▌    | 90/98 [00:15<00:01,  7.27it/s]

 93%|██████████████████████████████████████████████████▏   | 91/98 [00:15<00:01,  6.95it/s]

 94%|██████████████████████████████████████████████████▋   | 92/98 [00:16<00:00,  7.20it/s]

 95%|███████████████████████████████████████████████████▏  | 93/98 [00:16<00:00,  7.29it/s]

 96%|███████████████████████████████████████████████████▊  | 94/98 [00:16<00:00,  7.43it/s]

 97%|████████████████████████████████████████████████████▎ | 95/98 [00:16<00:00,  7.41it/s]

 98%|████████████████████████████████████████████████████▉ | 96/98 [00:16<00:00,  7.27it/s]

 99%|█████████████████████████████████████████████████████▍| 97/98 [00:16<00:00,  7.29it/s]

100%|██████████████████████████████████████████████████████| 98/98 [00:16<00:00,  5.78it/s]

**Ok, but we've done the same thing but we did not save it anywhere**

In [39]:
df_authors = pd.DataFrame({"author_id": all_authors,
                           "author_username": author_usernames})
df_authors

              author_id  author_username
0             311244158          e_jungd
1              74883793    GonzaloBarria
2    930217579800604672  KdXI8GYHGr8fz1s
3   1497870550332579845     LinaMpoumpou
4             940224440    frank29273107
..                  ...              ...
93           2579454504         xpgomes3
94  1113426385974984705    LindaMulcahy7
95           1527074713      AntennaNews
96             38631911          B3CPres
97  1541466817633419264  TraderRembrandt

[98 rows x 2 columns]

In [40]:
df = pd.merge(df, df_authors, how="left", on=["author_id"])

In [41]:
df

,author_id,text,created_at,lang,author_username
0,311244158,"RT @icp_uc: ¡Que orgullo!👏💪Yancy Villarroel, e...",2022-11-29 16:28:49+00:00,es,e_jungd
1,74883793,"RT @icp_uc: ¡Que orgullo!👏💪Yancy Villarroel, e...",2022-11-29 16:25:56+00:00,es,GonzaloBarria
2,930217579800604672,RT @evangelia_re: Πήγε ο Μητσοτάκης στο london...,2022-11-29 16:19:00+00:00,el,KdXI8GYHGr8fz1s
3,1497870550332579845,RT @evangelia_re: Πήγε ο Μητσοτάκης στο london...,2022-11-29 16:18:04+00:00,el,LinaMpoumpou
4,940224440,RT @evangelia_re: Πήγε ο Μητσοτάκης στο london...,2022-11-29 16:01:49+00:00,el,frank29273107
...,...,...,...,...,...
95,1527074713,Μητσοτάκης στο London School of Economics: Εφι...,2022-11-28 22:01:55+00:00,el,AntennaNews
96,1581543998090579968,RT @NikosKoudounis1: @kostasp1488 Ρελάνς του Τ...,2022-11-28 22:00:52+00:00,el,NikosKoudounis1
97,1581543998090579968,RT @NikosKoudounis1: @chris_avramidis @theodor...,2022-11-28 22:00:41+00:00,el,NikosKoudounis1
98,38631911,RT @BrexitBin: In case you missed it ...\nHere...,2022-11-28 21:46:12+00:00,en,B3CPres
99,1541466817633419264,György left Hungary in 1947 and studied econom...,2022-11-28 21:40:31+00:00,en,TraderRembrandt

# Extract tokens

Tokenisation is the process of segmenting text into words, punctuations marks etc.

We are going to use spaCy

## Which languages are involved?

In [42]:
df["lang"].value_counts()

en    49
el    43
es     5
in     2
de     1
Name: lang, dtype: int64

Check twitter API Documentation to check the languages: https://developer.twitter.com/en/docs/twitter-for-websites/supported-languages

## Let's focus on language='en' first

In [43]:
# Pick one random sample
sample = df.query("lang == 'en'").sample(1)

sample

,author_id,text,created_at,lang,author_username
57,1586632345129742336,"he waged\na relentless, lifelong struggle for ...",2022-11-29 10:05:46+00:00,en,MadrasTribes

In [45]:
just_the_text = sample["text"].values[0]
print(just_the_text)

he waged
a relentless, lifelong struggle for the rights of Dalits. Having
earned doctorates from both Columbia University and the
London School of Economics, went on to serve as Chairman
of the Drafting Committee of the Indian Constitution.

(2)

🗣️ **CLASSROOM DISCUSSION:** What does the following represent?

In [46]:
len(just_the_text)

245

In [47]:
type(just_the_text)

str

### Tokenization

**We need to load the language related features from spaCy**

In [48]:
from spacy.lang.en import English
language_parser = English()

tokenized_text = language_parser(just_the_text)
type(tokenized_text)

  0%|                                                               | 0/98 [12:26<?, ?it/s]

spacy.tokens.doc.Doc

In [49]:
tokenized_text

he waged
a relentless, lifelong struggle for the rights of Dalits. Having
earned doctorates from both Columbia University and the
London School of Economics, went on to serve as Chairman
of the Drafting Committee of the Indian Constitution.

(2)

🗣️ **CLASSROOM DISCUSSION:** What do you think the following represents?

In [50]:
len(tokenized_text)

50

In [222]:
for token in tokenized_text:
    print(token)

RT
@BrexitBin
:
In
case
you
missed
it
...


Here
's
an
excerpt
from
a
report
into
immigration
and
wages
by
the
London
School
of
Economics
.
It
s
…

**Silly way to count repeated tokens using `list comprehension`**

In [51]:
pd.Series([token for token in tokenized_text]).value_counts()

he              1
of              1
of              1
Economics       1
,               1
went            1
on              1
to              1
serve           1
as              1
Chairman        1
\n              1
the             1
waged           1
Drafting        1
Committee       1
of              1
the             1
Indian          1
Constitution    1
.               1
\n\n            1
(               1
2               1
School          1
London          1
\n              1
the             1
\n              1
a               1
relentless      1
,               1
lifelong        1
struggle        1
for             1
the             1
rights          1
of              1
Dalits          1
.               1
Having          1
\n              1
earned          1
doctorates      1
from            1
both            1
Columbia        1
University      1
and             1
)               1
dtype: int64

**Let's change everything to lowercase:**

In [224]:
new_tokenized_test = language_parser(just_the_text.strip().lower())

pd.Series([token for token in new_tokenized_test]).value_counts()

rt             1
report         1
s              1
it             1
.              1
economics      1
of             1
school         1
london         1
the            1
by             1
wages          1
and            1
immigration    1
into           1
a              1
@brexitbin     1
from           1
excerpt        1
an             1
's             1
here           1
\n             1
...            1
it             1
missed         1
you            1
case           1
in             1
:              1
…              1
dtype: int64

### Lemmatization

https://spacy.io/usage/linguistic-features#lemmatization

There are **pre-trained** fancy NLP models that can detect more interesting things about our text.

In [235]:
# You need to download the suitable NLP models https://spacy.io/models/en
#!python -m spacy download en_core_web_sm

In [53]:
import spacy

nlp = spacy.load("en_core_web_sm")

In [57]:
fancier_tokenized_text = nlp(just_the_text.strip().lower())

fancier_tokenized_text[1].lemma_

'wage'

In [63]:
my_tokens = [word.lemma_.lower().strip() if word.lemma_ != "-PRON-" else word.lower_ for word in fancier_tokenized_text ]

### Remove punctuation & stop words

In [64]:
import string

from spacy.lang.en.stop_words import STOP_WORDS

# Create our list of punctuation marks
punctuations = string.punctuation

# Stop words for the English language
stop_words = spacy.lang.en.stop_words.STOP_WORDS

# Removing stop words
my_tokens = [ word for word in my_tokens if word not in stop_words and word not in punctuations ]
my_tokens

['wage',
 'relentless',
 'lifelong',
 'struggle',
 'right',
 'dalit',
 'having',
 'earn',
 'doctorate',
 'columbia',
 'university',
 'london',
 'school',
 'economic',
 'serve',
 'chairman',
 'drafting',
 'committee',
 'indian',
 'constitution',
 '2']

In [243]:
len(my_tokens)

17

## Putting everything together: automating this process

Also, check [this tutorial](https://www.dataquest.io/blog/tutorial-text-classification-in-python-using-spacy/)

In [66]:
import string

from spacy.lang.en.stop_words import STOP_WORDS
from spacy.lang.en import English

# Create our list of punctuation marks
punctuations = string.punctuation

# Create our list of stopwords
nlp = spacy.load("en_core_web_sm")
stop_words = spacy.lang.en.stop_words.STOP_WORDS

def clean_text(tweet_text):
    simpler_text = tweet_text.strip().lower()
    mytokens = nlp(simpler_text)
    mytokens = [ word.lemma_.lower().strip() if word.lemma_ != "-PRON-" else word.lower_ for word in mytokens ]
    mytokens = [ word for word in mytokens if word not in stop_words and word not in punctuations ]
    return mytokens

Use pandas `apply` to make your code look cleaner!

In [70]:
df_en = df.query("lang == 'en'")

In [71]:
df_en["text"].apply(clean_text)

7     [rt, @pleaseletmevote, london, school, economi...
17    [director, international, programme, impact, l...
18    [tax, cut, wealthy, long, draw, support, conse...
23    [rt, @lag_uk, 📢, pleased, award, 2022, latin, ...
25    [rt, @fascinatorfun, loss, 20, pound, value, d...
32    [rt, @tanzania_epza, y'day, courtesy, visit, c...
33    [director, international, programme, impact, l...
34    [rt, @fascinatorfun, loss, 20, pound, value, d...
35    [london, school, economic, estimate, brexit, –...
36    [rt, @fascinatorfun, loss, 20, pound, value, d...
37    [rt, @lag_uk, 📢, pleased, award, 2022, latin, ...
39    [rt, @lag_uk, 📢, pleased, award, 2022, latin, ...
40    [london, school, economic, estimate, brexit, ....
41    [andy, vermaut, share, finance, employee, futu...
42    [rt, @lag_uk, 📢, pleased, award, 2022, latin, ...
43    [rt, @fascinatorfun, loss, 20, pound, value, d...
44    [rt, @fascinatorfun, loss, 20, pound, value, d...
45    [📢, pleased, award, 2022, latin, american, geo...
46    [rt, @fascinatorfun, loss, 20, pound, value, d...
47    [@danihas03237661, @rachelreevesmp, @uklabour,...
48    [rt, @fascinatorfun, loss, 20, pound, value, d...
49    [rt, @fascinatorfun, loss, 20, pound, value, d...
50    [rt, @fascinatorfun, loss, 20, pound, value, d...
51    [rt, @fascinatorfun, loss, 20, pound, value, d...
52    [rt, @fascinatorfun, loss, 20, pound, value, d...
53    [loss, 20, pound, value, dollar, 2016, london,...
57    [wage, relentless, lifelong, struggle, right, ...
58    [london, school, economic, estimate, brexit, –...
59    [rt, @rowanchss, dr, andrew, gooch, new, resea...
61    [rt, @pleaseletmevote, london, school, economi...
63    [rt, @pleaseletmevote, london, school, economi...
64    [bob, ward, policy, communication, director, l...
65    [london, school, economic, estimate, brexit, –...
75    [rt, @tanzania_epza, y'day, courtesy, visit, c...
76    [takeaway, financial, time, article, recent, i...
77    [rt, @tanzania_epza, y'day, courtesy, visit, c...
78    [y'day, courtesy, visit, consultant, london, s...
81    [study, jasmine, 6, year, economics, major, lo...
82    [rt, @buildconstdes, marshall, building, renow...
84    [early, jaggi, vasudev, founder, isha, foundat...
85    [@tedcruz, ted, cruz, job, btw, ted, cruz, wif...
86    [geopolitic, push, need, microgrid, power, hea...
87    [passfield, hall, london, school, economic, lo...
91    [rt, @nokianetwork, geopolitic, push, need, mi...
92    [rt, @brexitbin, case, miss, ..., excerpt, rep...
93    [rt, @africaatlse, want, build, world, 🌍, appl...
94    [rt, @paulfscott, big, job, klaxon, professor,...
98    [rt, @brexitbin, case, miss, ..., excerpt, rep...
99    [györgy, leave, hungary, 1947, study, economic...
Name: text, dtype: object

**There is a fancy tqdm for pandas**

In [72]:
from tqdm import tqdm
# from tqdm.auto import tqdm  # for notebooks

# Create new `pandas` methods which use `tqdm` progress
# (can use tqdm_gui, optional kwargs, etc.)
tqdm.pandas()

In [73]:
df_en["text"].progress_apply(clean_text)

100%|██████████████████████████████████████████████████████| 49/49 [00:01<00:00, 39.23it/s]

7     [rt, @pleaseletmevote, london, school, economi...
17    [director, international, programme, impact, l...
18    [tax, cut, wealthy, long, draw, support, conse...
23    [rt, @lag_uk, 📢, pleased, award, 2022, latin, ...
25    [rt, @fascinatorfun, loss, 20, pound, value, d...
32    [rt, @tanzania_epza, y'day, courtesy, visit, c...
33    [director, international, programme, impact, l...
34    [rt, @fascinatorfun, loss, 20, pound, value, d...
35    [london, school, economic, estimate, brexit, –...
36    [rt, @fascinatorfun, loss, 20, pound, value, d...
37    [rt, @lag_uk, 📢, pleased, award, 2022, latin, ...
39    [rt, @lag_uk, 📢, pleased, award, 2022, latin, ...
40    [london, school, economic, estimate, brexit, ....
41    [andy, vermaut, share, finance, employee, futu...
42    [rt, @lag_uk, 📢, pleased, award, 2022, latin, ...
43    [rt, @fascinatorfun, loss, 20, pound, value, d...
44    [rt, @fascinatorfun, loss, 20, pound, value, d...
45    [📢, pleased, award, 2022, latin, american, geo...
46    [rt, @fascinatorfun, loss, 20, pound, value, d...
47    [@danihas03237661, @rachelreevesmp, @uklabour,...
48    [rt, @fascinatorfun, loss, 20, pound, value, d...
49    [rt, @fascinatorfun, loss, 20, pound, value, d...
50    [rt, @fascinatorfun, loss, 20, pound, value, d...
51    [rt, @fascinatorfun, loss, 20, pound, value, d...
52    [rt, @fascinatorfun, loss, 20, pound, value, d...
53    [loss, 20, pound, value, dollar, 2016, london,...
57    [wage, relentless, lifelong, struggle, right, ...
58    [london, school, economic, estimate, brexit, –...
59    [rt, @rowanchss, dr, andrew, gooch, new, resea...
61    [rt, @pleaseletmevote, london, school, economi...
63    [rt, @pleaseletmevote, london, school, economi...
64    [bob, ward, policy, communication, director, l...
65    [london, school, economic, estimate, brexit, –...
75    [rt, @tanzania_epza, y'day, courtesy, visit, c...
76    [takeaway, financial, time, article, recent, i...
77    [rt, @tanzania_epza, y'day, courtesy, visit, c...
78    [y'day, courtesy, visit, consultant, london, s...
81    [study, jasmine, 6, year, economics, major, lo...
82    [rt, @buildconstdes, marshall, building, renow...
84    [early, jaggi, vasudev, founder, isha, foundat...
85    [@tedcruz, ted, cruz, job, btw, ted, cruz, wif...
86    [geopolitic, push, need, microgrid, power, hea...
87    [passfield, hall, london, school, economic, lo...
91    [rt, @nokianetwork, geopolitic, push, need, mi...
92    [rt, @brexitbin, case, miss, ..., excerpt, rep...
93    [rt, @africaatlse, want, build, world, 🌍, appl...
94    [rt, @paulfscott, big, job, klaxon, professor,...
98    [rt, @brexitbin, case, miss, ..., excerpt, rep...
99    [györgy, leave, hungary, 1947, study, economic...
Name: text, dtype: object

# Now what

Now that you have cleaned and tokenized everything, you can do the fun stuff:

## Bag of Words 

Use `CountVectorizer` from [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) package to create a bag of words

In [74]:
from sklearn.feature_extraction.text import CountVectorizer

bow_vector = CountVectorizer(tokenizer = clean_text, ngram_range=(1,1))

In [75]:
bow_vector.fit_transform(df.query("lang == 'en'")["text"])

<49x321 sparse matrix of type '<class 'numpy.int64'>'
	with 806 stored elements in Compressed Sparse Row format>

In [76]:
bow_vector.fit_transform(df.query("lang == 'en'")["text"]).todense().shape

(49, 321)

In [259]:
#bow_vector.get_feature_names_out()

In [77]:
df_bag_words = pd.DataFrame(bow_vector.fit_transform(df.query("lang == 'en'")["text"]).todense(),
                            columns=bow_vector.get_feature_names_out())

In [78]:
df_bag_words

,..,...,.....,01,08:46,1/3,16,1947,1951,1954,...,workin,world,wraptite,y'day,year,–,—,…,🌍,📢
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
8,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
12,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
34,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
35,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
36,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
37,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
38,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
39,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,0,0,0,1,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
44,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
45,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,1,0
46,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
48,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
l

**What are the most frequent tokens?**

In [79]:
df_bag_words.sum().sort_values(ascending=False).head(10)

london      45
school      44
economic    39
…           28
rt          28
20          12
brexit      12
loss        12
value       12
pound       12
dtype: int64

🗣️ **CLASSROOM DISCUSSION** What would you do with this data now?

### PCA + plotly

In [268]:
!pip install plotly==5.11.0

^C

In [271]:
## Train an algorithm called PCA

## Read more about it here https://scikit-learn.org/stable/modules/decomposition.html#pca

from sklearn.decomposition import PCA

pca = PCA()
components = pca.fit_transform(df_bag_words)

In [304]:
df_pca = pd.DataFrame(components, columns=[f"PC{i+1}" for i in range(components.shape[1])])